version: "3"
services:
  api:
    build: .
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "0.0.0.0:3000:3000"
    command: "yarn start:dev"
  db:
    image: postgres:11.5-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nest
    # Maps port 5432 (localhost) to port 5432 on the container. You can change the ports to fix your needs.
    ports:
      - "5432:5432"
    # Set a volume some that database is not lost after shutting down the container.
    # I used the name postgres-data but you can changed it to something else.
    volumes:
      - ./postgres-data:/var/lib/postgresql/data